name: Deploy to Staging Server

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install

      - name: build
        run: gulp build

      - name: Copy dist.zip to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST_STAGING }}
          username: ${{ secrets.SERVER_USERNAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          passphrase: ${{ secrets.PASSPHRASE_STAGING }}
          port: 88
          source: dist/
          target: ~/

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_STAGING }}
          username: ${{ secrets.SERVER_USERNAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          passphrase: ${{ secrets.PASSPHRASE_STAGING }}
          script: |
            # Copy the contents of dist/ to /var/www/
            sudo cp -r ~/dist/ /var/www/

            # Copy permissions from html/ to the new files in /var/www/
            sudo cp -rp /var/www/html/ /var/www/dist/

            # Delete the old html directory
            sudo rm -r /var/www/html

            # Rename dist/ to html/
            sudo mv /var/www/dist /var/www/html

            # Delete the old .zip file and unzipped directory
            rm -r ~/dist

          port: 88
